### ISSUE TITLE
[BUG] typo in `kbcli cluster edit-config` help

### ISSUE THREAD

**Issue by shawn0915** [apecloud/kbcli#350]
**Describe the bug**

typo here, need to update.

**To Reproduce**

```
[root@rocky9 ~]# kbcli cluster edit-config --help | egrep 'Opt|Usage|comp'
Edit the config file of the component.
Options:
    --components=[]:
	Boolean flag to restart component. Default with false.
Usage:
  kbcli cluster edit-config NAME [--component=component-name] [--config-spec=config-spec-name] [--config-file=config-file] [flags] [options]
[root@rocky9 ~]# 
```

**Expected behavior**

should be `--components` in Usage

**Screenshots**

![图片](https://github.com/apecloud/kbcli/assets/17957066/6adda314-41d7-4442-ae31-5ca57853ada3)

**Desktop (please complete the following information):**

```
[root@rocky9 ~]# kbcli version
Kubernetes: v1.23.8+k3s1
KubeBlocks: 0.8.2
kbcli: 0.8.2
```

**Additional context**

**Comment by Chiwency** [comment]
What's the scenario where you encounter this bug? I think it  should use 'component' instead of the plural form.
For example, the replication mode Redis has two components `redis` and `redis-sentinel`, we edit one of them by :
```bash
kbcli cluster edit-config  cluster-name --components redis   (the wrong using plural form currently)
# or 
kbcli cluster edit-config  cluster-name --components redis-sentinel
```
We can't edit both configs as once right?     So I think we should use `--component`
